name: stash_disk
version: 1.0.0-dev.1
description: >-
  Disk storage extension for the stash caching API. Provides support to store caches
  in the local file system in binary format using the msgpack json format
homepage: https://github.com/ivoleitao/stash_disk

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  stream_transform: ^1.2.0
  stash:
    path: ../stash

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.3
  test_coverage: ^0.4.1
